### ISSUE TITLE
version X.Y milestones

### ISSUE THREAD

**Issue by pmrv** [pyiron/pyiron#773]
As we are just discussed, we should collect the milestones before we want before the next (major) version bump:

Some points we mentioned as candidates
- docs
  - [ ] consistent documentation & website #779 
  - [ ] [high-level docs](https://www.joelonsoftware.com/2000/10/02/painless-functional-specifications-part-1-why-bother/), how do modules interact, reponsibilities
  - [ ] website polishing? 
- increase test coverage, 80%, candidate:
  - [ ] gaussian
  - [ ] gpaw
  - [ ] thermodynamics
  - [ ] dft, base & project are around ~50-60%
- [ ] use `InputList` for all major codes & remove `GenericParameters`
- [ ] ground work for pyiron/experimental (vs. making a separate module)
- [ ] pyiron GUI via [ipytree](https://github.com/QuantStack/ipytree)
- [ ] new Atoms class from ase
- [ ] protocol integration, lives currently in https://github.com/pyiron/pyiron_contrib 
- [ ] remote SQL database access, HDF-only installations?
- [ ] dynamic object loading from hdf (automatic from object metadata?)
- [ ] identify parts that can be split into separate repositories
  - [ ] `pyiron.base` is essentially standalone, everything else could be `atomistic`

As for the minor bump maybe 65d76edfa55e2e87b607549c0f1f0098ba6f8f4c.  That would be the commit just before merging the inputlist branch.

**Comment by ashtonmv** [comment]
Sudarsan's refactored Atoms class comes to mind- should we consider that to be a milestone?

**Comment by jan-janssen** [comment]
I would be interested to work on the database interface, mainly supporting clusters which do not have a local SQL database.

**Comment by pmrv** [comment]
> Sudarsan's refactored Atoms class comes to mind- should we consider that to be a milestone?

See I knew missed a bit.

**Comment by samwaseda** [comment]
I'd love to talk about the consistency with the website. A long standing issue is for example the output quantities, partially given [here](https://pyiron.github.io/source/faq.html#which-output-quantities-are-stored-in-pyiron), which VASP doesn't follow. But then there are also some stuff that should be updated as well I guess.

**Comment by raynol-dsouza** [comment]
I think a basic version of protocols (maybe NEB, for starters) could also be included.

**Comment by pmrv** [comment]
See #792, #793, #794, #795
